function []=interfaceF_launchPOSTMain(type, f2, aggregationInfo, commonDataInfo, flag_optim_dom, flag_aqi_dom, emi, global_data, base_emi_low, base_emi_high, CLE, ...
    base_emi_low_noc,base_emi_high_noc,paretoSolutions,pop, pm10aveToExceed, fidStatus,fidExit, localnnSuperSet, localDSuperSet, localbcSuperSet);

%if isequal(aggregationInfo.type, 'FIRSTGUESS')
if isequal(type, 'FIRSTGUESS')
    %localnnSuperSet=0;
    %overwrite value...
    localDSuperSet=firstguess_get_DSuperSet(aggregationInfo.geometryIntermediateData, 1);
    %localbcSuperSet=0;
    % 20160422 : MM Version First Guess/SR Version
    POSTmain_FG(f2,localDSuperSet,aggregationInfo,commonDataInfo.pathANN, commonDataInfo.flag_region_dom, flag_optim_dom, flag_aqi_dom,...
        commonDataInfo.domainData.coordinate,emi,global_data,base_emi_low,base_emi_high,CLE, ...
        base_emi_low_noc,base_emi_high_noc,commonDataInfo.dirs.pathOCM,paretoSolutions,...
        commonDataInfo.optim_flags.areal_point,commonDataInfo.optim_flags.reg_net,commonDataInfo.dirs.pathOUF,pop,commonDataInfo.info.nocID,commonDataInfo.dirs.pathAR,pm10aveToExceed,...
        commonDataInfo.cell_threshold_set,fidStatus,fidExit, commonDataInfo)
else
    % 20160422 : MM Version Quadrant/NN Version
    %localnnSuperSet=interface_get_nnSuperSet(aggregationInfo.mathIntermediateData);
    %localDSuperSet=interface_get_DSuperSet(aggregationInfo.geometryIntermediateData);
    %localbcSuperSet=interface_get_bcSuperSet(aggregationInfo.mathIntermediateData);
    global_data=commonDataInfo.special.global_data;
    POSTmain(f2,localnnSuperSet,localDSuperSet,localbcSuperSet,commonDataInfo.pathANN, commonDataInfo.flag_region_dom, flag_optim_dom, flag_aqi_dom,...
        commonDataInfo.domainData.coordinate,emi,global_data,base_emi_low,base_emi_high,CLE, ...
        base_emi_low_noc,base_emi_high_noc,commonDataInfo.dirs.pathOCM,paretoSolutions,...
        commonDataInfo.optim_flags.areal_point,commonDataInfo.optim_flags.reg_net,commonDataInfo.dirs.pathOUF,pop,commonDataInfo.info.nocID,commonDataInfo.dirs.pathAR,pm10aveToExceed,...
        commonDataInfo.cell_threshold_set,fidStatus,fidExit, commonDataInfo)
end

end

